#!/usr/bin/env php
<?php

declare(strict_types=1);

use Noffily\Teapot\Core\Runner;
use Noffily\Teapot\Core\Emitter;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Factory\AppFactory;
use Slim\Psr7\Factory\ServerRequestFactory;

require __DIR__ . '/vendor/autoload.php';

$app = AppFactory::create();
$app->addErrorMiddleware(true, true, true);
$app->get('/', function (ServerRequestInterface $request, ResponseInterface $response) {
    $response->getBody()->write('<a href="/hello/world">Try /hello/world</a>');
    return $response;
});
$app->get('/hello/{name}', function (ServerRequestInterface $request, ResponseInterface $response, $args) {
    $name = $args['name'];
    $response->getBody()->write("Hello, $name");
    return $response;
});

$emitter = new Emitter(Closure::fromCallable(function (ServerRequestInterface $request) use ($app) {
    return $app->handle($request);
}));

$loader = new \Noffily\Teapot\Core\Loader(__DIR__ . '/Tests');
$loader->execute(new Runner($emitter));

echo 'done' . PHP_EOL;