#!/usr/bin/env php
<?php

declare(strict_types=1);

use Noffily\Psr7\Test\{Runner, Emitter};
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Factory\AppFactory;
use Slim\Psr7\Factory\ServerRequestFactory;

require __DIR__ . '/vendor/autoload.php';

$app = AppFactory::create();
$app->addErrorMiddleware(true, true, true);
$app->get('/', function (ServerRequestInterface $request, ResponseInterface $response) {
    $response->getBody()->write('<a href="/hello/world">Try /hello/world</a>');
    return $response;
});
$app->get('/hello/{name}', function (ServerRequestInterface $request, ResponseInterface $response, $args) {
    $name = $args['name'];
    $response->getBody()->write("Hello, $name");
    return $response;
});

$emitter = new Emitter(Closure::fromCallable(function (ServerRequestInterface $request) use ($app) {
    return $app->handle($request);
}));

class TestCase {
    public function testHomePage(Runner $runner)
    {
        $request = (new ServerRequestFactory())->createServerRequest('GET', '/');

        $runner->addRequest($request);
        $result = $runner->execute();

        $result->seeResponseCodeIs(200);
    }

    public function testHello(Runner $runner)
    {
        $request = (new ServerRequestFactory())->createServerRequest('GET', '/hello/noffily');

        $runner->addRequest($request);
        $result = $runner->execute();

        $result->seeResponseCodeIs(200);
    }
}

$testCase = new TestCase();
$testCase->testHello(new Runner($emitter));
$testCase->testHomePage(new Runner($emitter));

echo 'done';